# Generated by Django 4.0.5 on 2022-07-02 05:08

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut_alumno', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('dv_alumno', models.CharField(max_length=1, verbose_name='DV')),
                ('p_nombre', models.CharField(max_length=15, verbose_name='Primer nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('ap_paterno', models.CharField(max_length=15)),
                ('ap_materno', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nac', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=25, null=True)),
                ('nivel_socio', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False, verbose_name='Ciudad')),
                ('nombre', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID ')),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Colegios',
                'db_table': 'colegio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='core.ciudad')),
            ],
            options={
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Problemas de Login'], [1, 'Consultas Generales'], [2, 'Consultas Administrativas/Financiamiento'], [3, 'Otros']])),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contactos',
                'db_table': 'Contacto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=1)),
                ('educacion', models.CharField(max_length=10)),
                ('letra', models.CharField(max_length=1)),
                ('id_colegio', models.ForeignKey(db_column='id_colegio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegio')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamenCono',
            fields=[
                ('id_examenenes', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_rendicion', models.DateField()),
                ('lenguaje', models.IntegerField()),
                ('matematica', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Examen de Diagnostico',
                'db_table': 'examen_cono',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False, verbose_name='Region Nro')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEmp',
            fields=[
                ('id_tipo_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_emp', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Empleado',
                'db_table': 'tipo_emp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibroClases',
            fields=[
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.curso')),
                ('annio_escolar', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name_plural': 'Libros de Clases',
                'db_table': 'libro_clases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sala', models.CharField(max_length=15)),
                ('id_colegio', models.ForeignKey(db_column='id_colegio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegio', verbose_name='Colegio')),
            ],
            options={
                'verbose_name_plural': 'Salas',
                'db_table': 'sala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut_profesor', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_profesor', models.CharField(max_length=1, verbose_name='DV')),
                ('p_nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('ap_paterno', models.CharField(max_length=15, verbose_name='Apellido')),
                ('ap_materno', models.CharField(blank=True, max_length=15, null=True)),
                ('especialidad', models.CharField(max_length=35)),
                ('fecha_contrato', models.DateField()),
                ('direccion', models.CharField(max_length=25)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='core.asignatura', verbose_name='Asignatura')),
                ('id_colegio', models.ForeignKey(blank=True, db_column='id_colegio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegio')),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('valor', models.IntegerField()),
                ('pago', models.CharField(max_length=1)),
                ('annio', models.IntegerField(null=True)),
                ('rut_alumno', models.ForeignKey(db_column='rut_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
            ],
            options={
                'verbose_name_plural': 'Matriculas',
                'db_table': 'matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_termino', models.CharField(max_length=5)),
                ('annio', models.IntegerField()),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='core.asignatura')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.DO_NOTHING, to='core.sala')),
                ('rut_profesor', models.ForeignKey(db_column='rut_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.profesor')),
            ],
            options={
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_emp', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('dv_emp', models.CharField(max_length=1, verbose_name='Digito Verificador')),
                ('p_nombre', models.CharField(max_length=15, verbose_name='Primer Nombre')),
                ('s_nombre', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Nombre')),
                ('ap_paterno', models.CharField(max_length=15, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion')),
                ('fecha_contrato', models.DateField()),
                ('id_colegio', models.ForeignKey(db_column='id_colegio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegio', verbose_name='Colegio')),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna', verbose_name='Comuna')),
                ('id_tipo_emp', models.ForeignKey(blank=True, db_column='id_tipo_emp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoemp', verbose_name='Tipo de Empleado')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='rut_profesor',
            field=models.OneToOneField(db_column='rut_profesor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profesor'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.DO_NOTHING, to='core.region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id_arancel', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=10)),
                ('valor', models.FloatField()),
                ('fecha_limite', models.DateField()),
                ('verificador', models.CharField(max_length=1)),
                ('rut_alumno', models.ForeignKey(db_column='rut_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
            ],
            options={
                'verbose_name_plural': 'Aranceles',
                'db_table': 'arancel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('rut_apoderado', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_apoderado', models.CharField(max_length=1, verbose_name='DV')),
                ('p_nombre', models.CharField(max_length=15)),
                ('s_nombre', models.CharField(max_length=15)),
                ('ap_paterno', models.CharField(max_length=15)),
                ('ap_materno', models.CharField(max_length=15)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=25)),
                ('id_colegio', models.ForeignKey(db_column='id_colegio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegio')),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna')),
            ],
            options={
                'verbose_name_plural': 'Apoderados',
                'db_table': 'apoderado',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_colegio',
            field=models.ForeignKey(db_column='id_colegio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_examenes',
            field=models.OneToOneField(db_column='id_examenes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.examencono'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut_apoderado',
            field=models.ForeignKey(db_column='rut_apoderado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.apoderado'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut_user', models.IntegerField(null=True)),
                ('cargo', models.IntegerField(choices=[[0, 'Sostenedor'], [1, 'Director'], [2, 'Subdirector Academico'], [4, 'Subdirector Administrativo y Finanzas'], [5, 'Asistente de Admision y Matriculas'], [6, 'Asistente de Administracion y Finanzas'], [7, 'Profesor'], [8, 'Alumno']], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_colegio', models.ForeignKey(db_column='id_colegio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegio', verbose_name='Colegio')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_observacion', models.DateTimeField()),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('rut_alumno', models.ForeignKey(db_column='rut_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
                ('rut_profesor', models.ForeignKey(blank=True, db_column='rut_profesor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profesor')),
                ('libro_clases_id_libro', models.ForeignKey(db_column='libro_clases_id_libro', on_delete=django.db.models.deletion.DO_NOTHING, to='core.libroclases')),
            ],
            options={
                'verbose_name_plural': 'Observaciones',
                'db_table': 'observacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('tipo_evaluacion', models.CharField(max_length=15)),
                ('fecha_evaluacion', models.DateField()),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='core.asignatura', verbose_name='Asignatura')),
                ('rut_alumno', models.ForeignKey(db_column='rut_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno', verbose_name='Alumno')),
                ('rut_profesor', models.ForeignKey(db_column='rut_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.profesor', verbose_name='Profesor')),
                ('id_libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, to='core.libroclases')),
            ],
            options={
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('verificador', models.CharField(max_length=10)),
                ('rut_alumno', models.ForeignKey(db_column='rut_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
                ('rut_profesor', models.ForeignKey(db_column='rut_profesor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.profesor')),
                ('id_libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, to='core.libroclases')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'managed': True,
            },
        ),
    ]
